markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

contact:
  email: hi@ricostacruz.com

permalink: "/p/:title.html"

# Google analytics
analytics:
  hostname: manilajs.com
  id: UA-38979948-1

defaults:
  - scope:
      path: ""
    values:
      layout: "article"
